<?php
include'connect.php';
$firma=$_GET["firma"];
$muracat_alan=$_GET["muracat_alan"];
$muracat_eden=$_GET["muracat_eden"];
$muracat_alan_gorev=$_GET["muracat_alan_gorev"];
$tel=$_GET["tel"];
$email=$_GET["email"];
$musteri_fatura_adres=$_GET["musteri_fatura_adres"];
$vd=$_GET["vd"];
$vno=$_GET["vno"];
$makine_tipi=$_GET["makine_tipi"];
$makine_seri_no=$_GET["makine_seri_no"];
$makine_model=$_GET["makine_model"];
$makine_marka=$_GET["makine_marka"];
$makinetcs=$_GET["makinetcs"];
$makineytcs=$_GET["makineytcs"];
$parola1=$_GET["parola1"];
$parola2=$_GET["parola2"];
$makine_adres=$_GET["makine_adres"];
$makine_atel=$_GET["makine_atel"];
$saatsonra=$_GET["saatsonra"];
$servistipi=$_GET["servistipi"];
$calismasaati=$_GET["calismasaati"];
$ariza=$_GET["ariza"];
$aciklamalar=$_GET["aciklamalar"];karşıla

$sql ="Update Dis_Servis_Formu set COLUMN muracat_alan $muracat_alan");
$conn->query($sql);
?>